### ISSUE TITLE
Option to prevent comment from being added?

### ISSUE THREAD

**Issue by dazinator** [Kajabity/Kajabity.Tools.Java#13]
Hi, I was just checking the java property writer out.
When using JavaProperties class and saving modifications, the resulting file always has a comment line added to the top indicating the current date. Is there a way to turn this off?

**Comment by Kajabity** [comment]
Hi, Dazinator,

Currently that line is always written - see https://github.com/Kajabity/Kajabity.Tools.Java/blob/master/Kajabity.Tools.Java/Java/JavaPropertyWriter.cs#L101.

However, I can probably add something to make it optional - a flag defaulting to true which can be set false by the calling class.

I'll have a look this evening/tomorrow and push the changes.

**Comment by Kajabity** [comment]
I've added a new method to `JavaProperties `-  `public void Store(Stream streamOut, bool outputTimestamp)` that allows you to specify no timestamp output (false).

This should be in the latest NuGet published - or just fetch the code and use locally.

Let me know if this is suitable - I'll close the defect in a couple of weeks if there are no more problems.

Hope this helps.

**Comment by dazinator** [comment]
@Kajabity - that's great, thank you very much! ;-)
