### ISSUE TITLE
Add .NET 5.0 Support

### ISSUE THREAD

**Issue by Kajabity** [Kajabity/Kajabity.Tools.Java#19]
Following a request to add support for building with .net core 5.0 framework.

**Comment by abrousseau001** [comment]
OBE - .NET 5 support was dropped May 2022. #22 adds .NET 6 support and all currently supported versions of .NET Framework supported as of a few days ago.

**Comment by Kajabity** [comment]
Closing as no longer required (see comment by @abrousseau001)
