### ISSUE TITLE
Add .net 6.0 support.

### ISSUE THREAD

**Issue by tianxin8206** [Kajabity/Kajabity.Tools.Java#21]
Following a request to add support for building with .net 6.0 framework.

**Comment by abrousseau001** [comment]
@tianxin8206 should have been taken care of by #22. This was merged into the codebase, but it seems like the AppVeyor CI/CD build is failing. Looks to be an authentication issue. @Kajabity is that something you can look into?

**Comment by Kajabity** [comment]
Now fixed by @abrousseau001.  Build and deploy now working after updating expired API keys.
