### ISSUE TITLE
Build failing on AppVeyor

### ISSUE THREAD

**Issue by abrousseau-hcgov** [Kajabity/Kajabity.Tools.Java#25]
Good afternoon @Kajabity,

I see the change I put in was merged, but the AppVeyor build is still failing. When you have a second, could you please check it out? I assume that build is what pushes the packages to NuGet, https://www.nuget.org/packages/Kajabity.Tools.Java/, which haven't been updated since the last time you were able to get AppVeyor working.

Thanks,

Adam Brousseau

**Comment by Kajabity** [comment]
I've made a few updates to the project including dependency versions, and fixed a few out of date API keys (and completed the change to 'main' branch).  I has now deployed as version 0.3.8895.38751.
Also, I hope to change to a tidier SemVer approach in the near future for version numbers.
Thanks for your efforts on this project.  Much appreciated.

**Comment by abrousseau-hcgov** [comment]
Thanks for taking care of that @Kajabity. I will close this issue out now that you have done the updates. I look forward to continuing our work together in the future.
