### ISSUE TITLE
JavaPropertyReader incorrectly reads files saved in UTF-8 with Byte Order Mark

### ISSUE THREAD

**Issue by romannort** [Kajabity/Kajabity.Tools.Java#3]
BinaryReader on the line below misinterprets BOM bytes as a part of a property key, resulting in incorrect keys being read.

https://github.com/Kajabity/Kajabity.Tools.Java/blob/e98df3a1e0795f76fb83388370ab74514693100c/Kajabity.Tools.Java/Java/JavaPropertyReader.cs#L304

Sample file with "key=value" pair to illustrate the issue:
[sample.zip](https://github.com/Kajabity/Kajabity.Tools.Java/files/2434279/sample.zip)

```C#
			var dic = new Dictionary<string, string>(1);

			JavaPropertyReader pr = new JavaPropertyReader(dic);

			pr.Parse(
				new FileStream(@"d:\_downloads\sample.properties", FileMode.Open), 
				new UTF8Encoding() 
			);

			//Output: '?key' equals 'key' ?  False
			Console.Out.WriteLine($" '{dic.Keys.First()}' equals 'key' ?  {dic.Keys.First().Equals("key").ToString()} ");

```

**Comment by Kajabity** [comment]
Thanks for letting me know - I'll have a look and see how best to fix it this week.

**Comment by romannort** [comment]
Thanks for the quick response.

Have some thoughts on it too. Will send a PR soon.
