### ISSUE TITLE
Can't detect duplicate keys within a single file

### ISSUE THREAD

**Issue by romannort** [Kajabity/Kajabity.Tools.Java#4]
Overwriting duplicate keys by default makes it impossible to catch duplicate 

key=value1
key=value2 

pairs within a single file. 

https://github.com/Kajabity/Kajabity.Tools.Java/blob/e98df3a1e0795f76fb83388370ab74514693100c/Kajabity.Tools.Java/Java/JavaPropertyReader.cs#L383

It's a major concern for me because of a huge number of properties within a single file.

How about adding an additional configuration switch to choose between non-throwing and throwing behaviors?

**Comment by Kajabity** [comment]
I have wondered about this myself and decided not to change it as this is following the standard behaviour for the Java Properties reader which ignores duplicates.  However, I agree that it would be useful to include a flag to cause an exception when a duplicate is read.  It would be useful as a debugging feature, if nothing else.
As with your other issue, I'll have a look this week.
