### ISSUE TITLE
Fails to parse files with newline inside a unicode escape

### ISSUE THREAD

**Issue by erezwanderman** [Kajabity/Kajabity.Tools.Java#7]
Consider a properties file like the following:
```
AAA\u\
0050=B
```
This is parsed correctly by Java's Properties class as key="AAAP" value="B".
However JavaPropertyReader class fails with the message "Invalid Unicode character".

Expected result is to parse correctly, as a backslash+newline sequence may appear anywhere in the middle of a unicode escape sequence, except from right after the backslash.

**Comment by Kajabity** [comment]
Thanks for raising this issue, and sorry for the delay.  I'll have a look to see how to fix it.

**Comment by Kajabity** [comment]
I've updated the escape handling to support terminators or line wrapping inside Unicode escapes.

I've also added a lot of missing or incomplete tests for both reading and writing, and validated them with the Java equivalents.

Updated to version 0.3.
