### ISSUE TITLE
JavaProperties.Store throws System.ArgumentException

### ISSUE THREAD

**Issue by AMArostegui** [Kajabity/Kajabity.Tools.Java#8]
On a .NET Core 3.1 console App, JavaProperties.Store method throws the above exception.

I also get the following extended information: 'iso-8859-2' is not a supported encoding name. For information on defining a custom encoding, see the documentation for the Encoding.RegisterProvider method. (Parameter 'name')

Indeed, the running the command: `System.Text.Encoding.GetEncoding("iso-8859-2")` raises the exception. Such line can be found in https://github.com/Kajabity/Kajabity.Tools.Java/blob/master/Kajabity.Tools.Java/Java/JavaPropertyWriter.cs , line 80.

Using _"iso-8859-1"_ (Is this the default encoding for Java properties files?) runs fine.

**Comment by Kajabity** [comment]
Hi, @AMArostegui, thanks for telling me about this.  

I'm having a look at it and I don't really remember why the code uses that encoding when the standard says it should be iso-8859-1.  That is the original commit so an original fault.

I'll try to fix it as soon as I can, but I'm struggling with an upgrade of Visual Studio at the moment and it looks like I've missed a couple of files from the repository.  Should be done this week.

**Comment by Kajabity** [comment]
While I haven't been able to reproduce the problem (it "Just Work" for me, I've now updated to use the correct encoding.

I noticed on https://docs.microsoft.com/en-us/dotnet/api/system.text.encoding?view=netcore-3.1 that this encoding has both .NET Framework and .NET Core support, while ISO-8859-2 has neither.

I hope this fixes your issue, but please let me know if it still causes problems.

**Comment by Kajabity** [comment]
Updated in version 0.2 but further fixes and much more unit testing in 0.3.
